title: Welcome to Maphybooks
description: >
  Download science and programming books for free.
permalink: ':title/'
url: "https://maphylibrary.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Admin # add your name
author-img: # add your photo
about-author: # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: maphylibrary # add your Github handle
social-email: # add your Email address

# Disqus
discus-identifier: maphylibrary # add your discus identifier

# Tracker
analytics: UA-119604099-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 12
paginate_path: "/page/:num"
